# Generated by Django 4.0.4 on 2022-05-06 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(help_text='Utilize o espaço para descrever a despesa em detalhes.', verbose_name='Descrição')),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9)),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=9)),
                ('parcelas', models.IntegerField(verbose_name='Quantidade de parcelas')),
                ('quitou', models.BooleanField(verbose_name='A despesa está completamente paga?')),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=20, unique=True, verbose_name='CPF ou CNPJ')),
                ('telefone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Nº da parcela')),
                ('vencimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('juros', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('pago_em', models.DateField(null=True)),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('despesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.despesa')),
            ],
        ),
        migrations.AddField(
            model_name='despesa',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.tipo_despesa'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.fornecedor'),
        ),
    ]
